image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/application
  PLAN: ${CI_PROJECT_DIR}/application/plan.tfplan

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/



before_script:
  #- rm -rf .terraform
  - terraform --version
  - cd application
#  - terraform init -backend-config=conf/beta-init.tfvars --reconfigure


stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  script:
    - terraform init -backend-config=conf/beta-init.tfvars --reconfigure
    - terraform validate

plan:
  stage: plan
  script:

    - terraform plan -var-file conf/beta.tfvars -out=$PLAN
  dependencies:
    - validate
  artifacts:
    name: plan
    paths:
      - $PLAN

apply:
  stage: apply
  script:
    - terraform apply -input=false $PLAN
  dependencies:
    - plan
  #when: manual