image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/application
  PLAN: ${CI_PROJECT_DIR}/application/plan.tfplan
  DEV_NAMESPACE: terraform-ecs
cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/plugins
    - ${TF_ROOT}/.terraform/providers


before_script:
  #- rm -rf .terraform
  - terraform --version
  - cd application
  - terraform init -backend-config=conf/beta-init.tfvars --reconfigure


stages:
  - validate
  - plan
  - apply
  - ecr

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:

    - terraform plan -var-file conf/beta.tfvars -out=$PLAN
  dependencies:
    - validate
  artifacts:
    name: plan
    paths:
      - $PLAN

apply:
  stage: apply
  script:
    - terraform apply -input=false $PLAN
  dependencies:
    - plan
  #when: manual

ecr:
  stage: ecr
  script:
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - export REPOSITORY_URI=$(aws ssm get-parameter --name "/${DEV_NAMESPACE}/ecr/uri" --query Parameter.Value --output text)
    - docker build -t $REPOSITORY_URI:2048 .
    - docker tag $REPOSITORY_URI:2048 $REPOSITORY_URI:$CI_COMMIT_SHORT_SHA
    - docker push $REPOSITORY_URI:2048
    - docker push $REPOSITORY_URI:$CI_COMMIT_SHORT_SHA
  dependencies:
    - apply