image:
  name: hashicorp/terraform:0.15.5
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/application
  PLAN: ${CI_PROJECT_DIR}/application/plan.tfplan
  DEV_NAMESPACE: terraform-ecs
  TF_OUTPUT: ${CI_PROJECT_DIR}/application/output.json
  #DOCKER_HOST: tcp://docker:2375/


.base-terraform:
  image:
  name: hashicorp/terraform:0.15.5
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  variables:
    TF_IN_AUTOMATION: "true"
#    TF_CLI_ARGS: "-input=false"
  before_script:
    - terraform --version
    - echo terraform -chdir=${TF_ROOT} init -backend-config=conf/beta-init.tfvars --reconfigure

    - terraform -chdir=${TF_ROOT} init -backend-config=conf/beta-init.tfvars --reconfigure

  cache:
    key: "${TF_ROOT}"
    paths:
      - ${TF_ROOT}/.terraform/plugins
      - ${TF_ROOT}/.terraform/providers
      

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/plugins
    - ${TF_ROOT}/.terraform/providers


before_script:
  - terraform --version
  - terraform -chdir=${TF_ROOT} init -backend-config=conf/beta-init.tfvars --reconfigure


stages:
  - validate
  - plan
  - apply
  - ecr

validate:
  stage: validate
  script:

    - terraform validate

plan:
  stage: plan
  script:

    - terraform -chdir=${TF_ROOT} plan -var-file conf/beta.tfvars -out=$PLAN

  dependencies:
    - validate
  artifacts:
    name: plan
    paths:
      - $PLAN

apply:
  stage: apply
  script:
    - terraform -chdir=${TF_ROOT} apply -input=false $PLAN
    - terraform -chdir=${TF_ROOT} output -json > $TF_OUTPUT
  dependencies:
    - plan
  artifacts:
    paths:
      - $TF_OUTPUT
    expire_in: 1 week
  #when: manual

ecr:
  stage: ecr
  image: docker:19.03.12
  #image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
  services:
    - docker:19.03.12-dind
  before_script:
    - apk add --no-cache curl jq wget unzip python3 py-pip
    - pip install awscli
    - aws --version
    - docker --version
    - cd application
  script:
    - echo getting REPOSITORY_URI from AWS SSM
    - REPOSITORY_URI=$(aws ssm get-parameter --name "/${DEV_NAMESPACE}/ecr/uri" --query Parameter.Value --output text)
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
    - docker build -t $REPOSITORY_URI:2048 .
    - docker tag $REPOSITORY_URI:2048 $REPOSITORY_URI:$CI_COMMIT_SHORT_SHA
    - docker push $REPOSITORY_URI:2048
    - docker push $REPOSITORY_URI:$CI_COMMIT_SHORT_SHA
    - export CLUSTER=$(jq -r .cluster.value $TF_OUTPUT)
    - export SERVICE=$(jq -r .service.value $TF_OUTPUT)
    - echo SERVICE $SERVICE CLUSTER $CLUSTER
    - aws ecs update-service --cluster $CLUSTER --service $SERVICE

    #- aws ecs update-service --cluster $(terraform output -json | jq -r .cluster.value) --service $(terraform output -json | jq -r .service.value)
  dependencies:
    - apply
  artifacts:
    name: TF_OUTPUT
    paths:
      - $TF_OUTPUT